# 测试环境配置
management:
  endpoints:
    web:
      exposure:
        # 线上环境仅暴露prometheus
        include: prometheus
spring:
  #  mail:
  #    host: smtp.qq.com
  #    port: 465
  #    protocol: smtp
  #    default-encoding: UTF-8
  #    username: 990885290@qq.com
  #    properties:
  #      mail:
  #        smtp:
  #          socketFactory:
  #            class: javax.net.ssl.SSLSocketFactory
  #    password: cqnusmjmlcslbddd
  application:
    name: binance-mining-ai-assistant
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    idle-timeout: 600000
    maximum-pool-size: 100
    max-lifetime: 1800000
    minimum-idle: 5
  redis:
    # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    lettuce:
      shutdown-timeout: 60000
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 80
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        # 连接池中的最大空闲连接
        max-idle: 80
        # 连接池中的最小空闲连接
        min-idle: 50
server:
  port: 8084

#mybatis驼峰字段映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true


#swagger:
#  enable: false
springdoc:
  swagger-ui:
    enabled: false


logging:
  level:
    root: info
    com:
      company: debug
  path: ./logs
pool:
  security:
    name:
      #矿池业务库
      db1:
        # securityName
        - bp-prod-tk-aws-pool-rds-key
        # securityRegion
        - ap-northeast-1
      #矿池业务库读库
      dbRead:
        # securityName
        - bp-prod-tk-aws-pool-replica-rds-key
        # securityRegion
        - ap-northeast-1
      #redis配置
      redis:
        - bp-prod-tk-aws-webapi-redis-key
        - ap-northeast-1
      #dbsecre配置
      dbSecretkey:
        - bp-beta-tk-dbrecordcheck-key
        - ap-northeast-1
  # 是否是线上的请求     # 是否是线上的请求 0 是测试还
  online: 1
  cancelAlgoId:
  domain: http://tk-dev-mpapi-out-lb-1665925952.ap-northeast-1.elb.amazonaws.com

